import
  Complexitylib.TimeSpaceSimulation.Runtime.NeighborhoodMicrocode.CombineTerm.Defs

open Complexity Complexity.TimeSpaceSimulation.Runtime.NeighborhoodMicrocode

#check CombineTerm.ComputationPackedKernelSpecAt
#print CombineTerm.ComputationPackedKernelSpecAt
