/-
Copyright (c) 2026 Samuel Schlesinger. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Samuel Schlesinger
-/
import Complexitylib.TimeSpaceSimulation.ComplexityBridge.Defs
import Complexitylib.TimeSpaceSimulation.NeighborhoodGraph.DecisionRecovery.Defs
import Complexitylib.TimeSpaceSimulation.NeighborhoodGraph.Guess.Defs
import Complexitylib.TreeEvaluation.Workspace.Defs
import Mathlib.Data.Nat.Size

/-!
# Direct evaluation of guessed neighborhood graphs

This definitions layer gives a total, direct Cook--Mertz traversal of a
guessed neighborhood graph. It never constructs the semantic tree: every
recursive child is regenerated from `CenterGuess.predecessorAt?`.

Malformed center prefixes and out-of-horizon computation nodes become an
explicit failure leaf. A fuel parameter bounds recursive height and is
decreased at every call. The intended two-query execution evaluates the
chronological state root and latest verdict-block root sequentially, retaining
the maximum rather than the sum of their live-frame peaks.

`passesLocalChecks` is executable but deliberately takes a separate
`CenterOracle`. Instantiating that oracle by a space-bounded local replay, and
proving that replay correct, is a separate obligation. In particular,
`CenterGuess.IsValidFor` is not used as a runtime test.
-/

namespace Complexity

namespace TimeSpaceSimulation

namespace NeighborhoodEvaluator

open NeighborhoodGraph
open TreeEval CookMertz

/-- Fixed fan-in of the direct three-block neighborhood graph. -/
def fanIn (workTapeCount : ℕ) : ℕ :=
  4 * (workTapeCount + 2)

/-- A direct evaluator node. `failure` is an explicit leaf reached after a
malformed guessed-center prefix or an out-of-horizon request. -/
inductive QueryNode (workTapeCount horizon : ℕ) where
  /-- Explicit failure leaf. -/
  | failure
  /-- A source or computation node of the neighborhood graph. -/
  | graph (node : Node workTapeCount)
  deriving DecidableEq

namespace QueryNode

/-- Interval rank, with the explicit failure leaf at rank zero. -/
def rank : QueryNode workTapeCount horizon → ℕ
  | .failure => 0
  | .graph node => node.rank

end QueryNode

/-- Regenerate one recursive child directly from the center guess.

The source and failure cases are never queried by the evaluator, so their
default failure child is only a totality convention. -/
def childAt (guess : Guess.CenterGuess workTapeCount horizon) :
    QueryNode workTapeCount horizon →
      Fin (fanIn workTapeCount) → QueryNode workTapeCount horizon
  | .failure, _ => .failure
  | .graph (.source _ _), _ => .failure
  | .graph (.computation _ _ interval), index =>
      if hinterval : interval < horizon then
        match guess.predecessorAt? ⟨interval, hinterval⟩ index with
        | none => .failure
        | some node => .graph node
      else
        .failure

/-- Fuel-bounded semantic unrolling used only as a correctness certificate.

The executable evaluator below follows the same recursion directly and does
not take this tree as input. -/
def unroll (guess : Guess.CenterGuess workTapeCount horizon)
    (failureValue : V)
    (sourceValue : TapeIndex workTapeCount → ℕ → V)
    (combine : TapeIndex workTapeCount → Slot → ℕ →
      (Fin (fanIn workTapeCount) → V) → V) :
    ℕ → QueryNode workTapeCount horizon →
      TreeEval.Tree (fanIn workTapeCount) V
  | _, .failure => .leaf failureValue
  | _, .graph (.source tape block) => .leaf (sourceValue tape block)
  | 0, .graph (.computation _ _ _) => .leaf failureValue
  | fuel + 1, node@(.graph (.computation tape slot interval)) =>
      if _hinterval : interval < horizon then
        .node
          (fun index =>
            unroll guess failureValue sourceValue combine fuel
              (childAt guess node index))
          (combine tape slot interval)
      else
        .leaf failureValue

/-- Direct, fuel-bounded Cook--Mertz traversal with a live-frame profile.

Children are regenerated by `childAt`; no `Tree` value occurs in this
definition. -/
def profileAccumulate [Field F] [AddCommGroup V] [Module F V]
    (units : List Fˣ) (guess : Guess.CenterGuess workTapeCount horizon)
    (failureValue : V)
    (sourceValue : TapeIndex workTapeCount → ℕ → V)
    (combine : TapeIndex workTapeCount → Slot → ℕ →
      (Fin (fanIn workTapeCount) → V) → V) :
    ℕ → QueryNode workTapeCount horizon → F →
      Fin (fanIn workTapeCount + 1) →
      Registers (fanIn workTapeCount) V →
      Workspace.Profile (Registers (fanIn workTapeCount) V)
  | _, .failure, scale, out, regs =>
      Workspace.Profile.start
        (addAt regs out (scale • failureValue))
  | _, .graph (.source tape block), scale, out, regs =>
      Workspace.Profile.start
        (addAt regs out (scale • sourceValue tape block))
  | 0, .graph (.computation _ _ _), scale, out, regs =>
      Workspace.Profile.start
        (addAt regs out (scale • failureValue))
  | fuel + 1, node@(.graph (.computation tape slot interval)),
      scale, out, regs =>
      if _hinterval : interval < horizon then
        units.foldl (fun current (unit : Fˣ) =>
          let current :=
            (List.finRange (fanIn workTapeCount)).foldl
              (fun current childIndex =>
                let target := out.succAbove childIndex
                let child :=
                  profileAccumulate units guess failureValue sourceValue
                    combine fuel (childAt guess node childIndex) 1 target
                    (scaleAt current.result target (unit : F))
                Workspace.Profile.recordChild current child)
              current
          let args := fun childIndex =>
            current.result (out.succAbove childIndex)
          let current :=
            Workspace.Profile.map
              (fun currentRegs =>
                addAt currentRegs out
                  ((-scale) • combine tape slot interval args))
              current
          (List.finRange (fanIn workTapeCount)).foldl
            (fun current childIndex =>
              let target := out.succAbove childIndex
              let child :=
                profileAccumulate units guess failureValue sourceValue
                  combine fuel (childAt guess node childIndex) (-1) target
                  current.result
              Workspace.Profile.map
                (fun currentRegs =>
                  scaleAt currentRegs target (↑unit⁻¹ : F))
                (Workspace.Profile.recordChild current child))
            current)
          (Workspace.Profile.start regs)
      else
        Workspace.Profile.start
          (addAt regs out (scale • failureValue))

/-- Direct evaluation from zero catalytic registers. -/
def profileEvaluate [Field F] [AddCommGroup V] [Module F V]
    (units : List Fˣ) (guess : Guess.CenterGuess workTapeCount horizon)
    (failureValue : V)
    (sourceValue : TapeIndex workTapeCount → ℕ → V)
    (combine : TapeIndex workTapeCount → Slot → ℕ →
      (Fin (fanIn workTapeCount) → V) → V)
    (fuel : ℕ) (node : QueryNode workTapeCount horizon) :
    Workspace.Profile V :=
  Workspace.Profile.map
    (fun regs => regs (Fin.last (fanIn workTapeCount)))
    (profileAccumulate units guess failureValue sourceValue combine
      fuel node 1 (Fin.last (fanIn workTapeCount)) 0)

/-- Guessed chronological root carrying the state at `horizon`. -/
def stateRoot (guess : Guess.CenterGuess workTapeCount horizon) :
    QueryNode workTapeCount horizon :=
  match horizon with
  | 0 =>
      .graph (.source (TapeIndex.input workTapeCount)
        (guess.initialCenter (TapeIndex.input workTapeCount)))
  | previous + 1 =>
      .graph (.computation
        (TapeIndex.input workTapeCount) .center previous)

/-- Guessed latest-copy root for one named block at `horizon`. -/
def latestBlockRoot (guess : Guess.CenterGuess workTapeCount horizon)
    (tape : TapeIndex workTapeCount) (block : ℕ) :
    QueryNode workTapeCount horizon :=
  match guess.previousInterval tape block horizon with
  | none => .graph (.source tape block)
  | some previous =>
      match guess.derivedCenter tape previous.val with
      | none => .failure
      | some center =>
          .graph (.computation tape
            (matchingSlot center block) previous.val)

/-- Guessed latest output-block root containing verdict cell `1`. -/
def verdictRoot (guess : Guess.CenterGuess workTapeCount horizon)
    (blockLength : ℕ) : QueryNode workTapeCount horizon :=
  latestBlockRoot guess (TapeIndex.output workTapeCount)
    (blockIndex blockLength 1)

/-- Execute the state and verdict queries sequentially.

The result pairs their values; the peak is the maximum because the same
catalytic bank and call stack are reused between the two traversals. -/
def profileDecision [Field F] [AddCommGroup V] [Module F V]
    (units : List Fˣ) (guess : Guess.CenterGuess workTapeCount horizon)
    (blockLength : ℕ) (failureValue : V)
    (sourceValue : TapeIndex workTapeCount → ℕ → V)
    (combine : TapeIndex workTapeCount → Slot → ℕ →
      (Fin (fanIn workTapeCount) → V) → V) :
    Workspace.Profile (V × V) :=
  let state :=
    profileEvaluate units guess failureValue sourceValue combine
      horizon (stateRoot guess)
  let verdict :=
    profileEvaluate units guess failureValue sourceValue combine
      horizon (verdictRoot guess blockLength)
  ⟨(state.result, verdict.result),
    max state.peakFrames verdict.peakFrames⟩

/-- Balanced block length used for one explicit candidate-time trial. -/
def candidateBlockLength (candidateTime : ℕ) : ℕ :=
  ComplexityBridge.balancedBlockLength candidateTime

/-- Finite interval horizon covering one explicit candidate-time trial. -/
def candidateHorizon (candidateTime : ℕ) : ℕ :=
  ComplexityBridge.timeBlockCount candidateTime

/-- Evaluate one explicit candidate time.

No source time bound or `actualTime` function is an argument. A future
simulator can invoke this wrapper for streamed candidates `n, n + 1, ...`
and halt only after a locally checked halted snapshot. -/
def profileCandidate [Field F] [AddCommGroup V] [Module F V]
    (units : List Fˣ) (candidateTime : ℕ)
    (guess : Guess.CenterGuess workTapeCount
      (candidateHorizon candidateTime))
    (failureValue : V)
    (sourceValue : TapeIndex workTapeCount → ℕ → V)
    (combine : TapeIndex workTapeCount → Slot → ℕ →
      (Fin (fanIn workTapeCount) → V) → V) :
    Workspace.Profile (V × V) :=
  profileDecision units guess (candidateBlockLength candidateTime)
    failureValue sourceValue combine

/-- Peak workspace of streamed trials, reusing all evaluator storage between
candidates. -/
def streamedPeak : List ℕ → ℕ :=
  List.foldl max 0

/-- A separate finite callback supplying locally computed center blocks.

The eventual concrete evaluator must produce `endCenter` by replaying one
interval from evaluated predecessor contents. This structure merely fixes
the executable checking interface. -/
structure CenterOracle (workTapeCount horizon : ℕ) where
  /-- Center block of each named tape in the initial configuration. -/
  initialCenter : TapeIndex workTapeCount → ℕ
  /-- Locally replayed end center after each interval. -/
  endCenter : Fin horizon → TapeIndex workTapeCount → ℕ

/-- Semantic reference oracle obtained from the frozen source run.

This is useful for correctness statements, but it is not the promised
space-bounded local-replay implementation. -/
def semanticCenterOracle (tm : TM workTapeCount) (x : List Bool)
    (blockLength horizon : ℕ) :
    CenterOracle workTapeCount horizon where
  initialCenter := fun tape =>
    centerBlock tm x blockLength 0 tape
  endCenter := fun interval tape =>
    centerBlock tm x blockLength (interval.val + 1) tape

/-- The oracle describes a given complete center trajectory. -/
def CenterOracle.AgreesWith
    (oracle : CenterOracle workTapeCount horizon)
    (trajectory : TapeIndex workTapeCount → ℕ → ℕ) : Prop :=
  (∀ tape, oracle.initialCenter tape = trajectory tape 0) ∧
  ∀ interval tape,
    oracle.endCenter interval tape =
      trajectory tape (interval.val + 1)

/-- Prefix-local soundness contract for an end-center replay callback.

At interval `i`, the callback need only be correct assuming the guessed
centers through `i` are correct. This is the contract supplied by a genuine
local simulation proof and is strictly weaker than knowing the entire
trajectory in advance. -/
def CenterOracle.IsPrefixSoundFor
    (oracle : CenterOracle workTapeCount horizon)
    (guess : Guess.CenterGuess workTapeCount horizon)
    (trajectory : TapeIndex workTapeCount → ℕ → ℕ) : Prop :=
  (∀ tape, oracle.initialCenter tape = trajectory tape 0) ∧
  ∀ interval,
    (∀ (earlier : Fin (horizon + 1)), earlier.val ≤ interval.val →
      ∀ tape,
        guess.derivedCenter tape earlier.val =
          some (trajectory tape earlier.val)) →
    ∀ tape,
      oracle.endCenter interval tape =
        trajectory tape (interval.val + 1)

/-- Executably check initial centers and every locally replayed interval end.

This is not a check against `actualCenterTrajectory`: the latter appears only
in a semantic soundness theorem after a concrete local-replay oracle has been
proved correct. -/
def passesLocalChecks
    (guess : Guess.CenterGuess workTapeCount horizon)
    (oracle : CenterOracle workTapeCount horizon) : Bool :=
  decide
    ((∀ tape, guess.initialCenter tape = oracle.initialCenter tape) ∧
      ∀ interval tape,
        guess.derivedCenter tape (interval.val + 1) =
          some (oracle.endCenter interval tape))

/-- One recursive-descent transition of the direct evaluator's live stack. -/
inductive ChildStep
    (guess : Guess.CenterGuess workTapeCount horizon) :
    QueryNode workTapeCount horizon →
      QueryNode workTapeCount horizon → Prop where
  /-- Enter one regenerated child of an in-horizon computation node. -/
  | computation
      (tape : TapeIndex workTapeCount) (slot : Slot)
      (interval : ℕ) (hinterval : interval < horizon)
      (index : Fin (fanIn workTapeCount)) :
      ChildStep guess
        (childAt guess
          (.graph (.computation tape slot interval)) index)
        (.graph (.computation tape slot interval))

/-- Every possible live call stack of the direct recursive evaluator.

Local arithmetic and loop-control transitions leave this stack unchanged;
only `push` represents a recursive call. -/
inductive ActiveStack
    (guess : Guess.CenterGuess workTapeCount horizon)
    (root : QueryNode workTapeCount horizon) :
    List (QueryNode workTapeCount horizon) → Prop where
  /-- The initial stack contains only the root call. -/
  | root : ActiveStack guess root [root]
  /-- A recursive call pushes one regenerated child. -/
  | push {child parent tail}
      (hstack : ActiveStack guess root (parent :: tail))
      (hchild : ChildStep guess child parent) :
      ActiveStack guess root (child :: parent :: tail)

/-- Fixed-width storage choices for the direct evaluator.

The frame width charges a node identifier, phase/counters, field scalars, and
register/child indices. Callback scratch is global and reused, rather than
multiplied by recursion depth. -/
structure StorageLayout where
  /-- Bits used for the guessed initial centers. True TM initial centers are
  all zero, but the generic evaluator keeps this charge explicit. -/
  initialCenterBits : ℕ
  /-- Bits occupied by the persistent `d + 1` catalytic register bank. -/
  catalyticBankBits : ℕ
  /-- Assigned width of one encoded query-node identifier. A concrete
  implementation must prove that every reachable identifier fits. -/
  nodeIdentifierBits : ℕ
  /-- Assigned width of phase tags and non-field local control. -/
  controlBits : ℕ
  /-- Bit width of one field scalar and unit-enumeration index. -/
  fieldBits : ℕ
  /-- Global scratch used by source, predecessor, node, and field callbacks. -/
  callbackScratchBits : ℕ

/-- Two bits encode each movement trit. -/
def movementBitBudget (workTapeCount horizon : ℕ) : ℕ :=
  2 * horizon * (workTapeCount + 2)

/-- Candidate bit width of a fixed-horizon query-node identifier.

The layout uses two tag bits, a named-tape index, a two-bit slot, and one
horizon-bounded block/interval index. This arithmetic definition is not by
itself a proof that arbitrary guessed source blocks satisfy the horizon
bound. -/
def nodeBitBudget (workTapeCount horizon : ℕ) : ℕ :=
  4 + (workTapeCount + 1).size + (horizon + 1).size

/-- Exact width assigned to one live recursive frame in the chosen layout.

Besides the separately certified node and control widths, one scale scalar,
one unit index, one output-register index, and one child-loop index are
charged. -/
def frameBitBudget (layout : StorageLayout)
    (workTapeCount : ℕ) : ℕ :=
  layout.nodeIdentifierBits + layout.controlBits +
    2 * layout.fieldBits +
    (fanIn workTapeCount).size +
    (fanIn workTapeCount - 1).size

/-- Exact assigned charge for an evaluator prefix with `liveFrames` calls.

Using these numbers as an encoding theorem additionally requires proofs that
the concrete node/control/callback representations fit the assigned fields. -/
def prefixBitUsage (layout : StorageLayout)
    (workTapeCount horizon liveFrames : ℕ) : ℕ :=
  layout.initialCenterBits +
    movementBitBudget workTapeCount horizon +
    layout.catalyticBankBits +
    liveFrames * frameBitBudget layout workTapeCount +
    layout.callbackScratchBits

/-- Height-indexed peak bound for either query and hence their sequential
composition. -/
def peakBitBound (layout : StorageLayout)
    (workTapeCount horizon : ℕ) : ℕ :=
  prefixBitUsage layout workTapeCount horizon (horizon + 1)

/-- Assigned peak-bit bound for one explicit candidate-time trial. -/
def candidatePeakBitBound (layout : StorageLayout)
    (workTapeCount candidateTime : ℕ) : ℕ :=
  peakBitBound layout workTapeCount (candidateHorizon candidateTime)

end NeighborhoodEvaluator

end TimeSpaceSimulation

end Complexity
