/-
Copyright (c) 2026 Samuel Schlesinger. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Samuel Schlesinger
-/
import
  Complexitylib.TimeSpaceSimulation.Runtime.NeighborhoodProgram.InstanceBounds.Defs
import
  Complexitylib.TimeSpaceSimulation.Runtime.NeighborhoodProgram.InstanceBounds.Internal

/-!
# Operational bounds for runtime neighborhood instances

These theorems expose the exact center and graph-node bounds forced by the
numeric movement-code provenance in `ResidueInstance`.
-/

namespace Complexity
namespace TimeSpaceSimulation
namespace Runtime
namespace NeighborhoodProgram
namespace InstanceBounds

open NeighborhoodGraph

/-- Every named tape starts at center block zero in a runtime trial guess. -/
theorem guess_initialCenter_eq_zero
    {workTapeCount : ℕ} {tm : TM workTapeCount}
    (instanceData : ResidueInstance tm)
    (tape : TapeIndex workTapeCount) :
    instanceData.guess.initialCenter tape = 0 :=
  Internal.guess_initialCenter_eq_zero_internal instanceData tape

/-- A successfully derived center advances by at most one block per
interval. -/
theorem derivedCenter_le
    {workTapeCount : ℕ} {tm : TM workTapeCount}
    (instanceData : ResidueInstance tm)
    (tape : TapeIndex workTapeCount)
    {boundary center : ℕ}
    (hcenter :
      instanceData.guess.derivedCenter tape boundary = some center) :
    center ≤ boundary :=
  Internal.derivedCenter_le_internal instanceData tape hcenter

/-- Every regenerated fixed-index predecessor fits the instance horizon. -/
theorem predecessorAt?_within
    {workTapeCount : ℕ} {tm : TM workTapeCount}
    (instanceData : ResidueInstance tm)
    (interval : Fin instanceData.horizon)
    (index :
      Fin (NeighborhoodExecutableEvaluation.graphFanIn workTapeCount))
    {node : Node workTapeCount}
    (hnode :
      instanceData.guess.predecessorAt? interval index = some node) :
    NodeWithin instanceData.horizon node :=
  Internal.predecessorAt?_within_internal
    instanceData interval index hnode

/-- Every child regenerated by the scheduler is a bounded query node. -/
theorem childAt_within
    {workTapeCount : ℕ} {tm : TM workTapeCount}
    (instanceData : ResidueInstance tm)
    (query :
      NeighborhoodEvaluator.QueryNode
        workTapeCount instanceData.horizon)
    (index :
      Fin (NeighborhoodExecutableEvaluation.graphFanIn workTapeCount)) :
    QueryNodeWithin instanceData.horizon
      (NeighborhoodEvaluator.childAt instanceData.guess query index) :=
  Internal.childAt_within_internal instanceData query index

end InstanceBounds
end NeighborhoodProgram
end Runtime
end TimeSpaceSimulation
end Complexity
